// Demo data: Maria Muster, 34, Zürich
// Static dataset that triggers all syntheses. Never written to localStorage.

export const DEMO_DATA = {
  basis: {
    firstName: 'Maria',
    middleName: '',
    lastName: 'Muster',
    dateOfBirth: '1992-03-15',
    gender: 'female',
    nationality: 'swiss',
    canton: 'ZH',
    phone: '+41 76 432 18 95',
    email: 'maria.muster@example.ch',
    ahv: '756.1234.5678.97',
    maritalStatus: 'single',
    dependents: '0',
    household: { adults: 1, children: [], isRetired: false },
  },
  wohnen: {
    address: 'Langstrasse 42',
    postalCode: '8004',
    city: 'Zürich',
    moveInDate: '2021-08-01',
    rentAmount: '1650',
    utilities: '180',
    landlord: 'Steiner Immobilien AG',
    landlordPhone: '+41 44 312 55 00',
    mortgageStatus: '',
    propertyValue: '',
    buildingsInsurance: '',
    residenceType: 'main',
  },
  finanzen: {
    monthlyIncome: '6200',
    employer: 'Kantonsspital Zürich',
    employmentType: 'employed',
    startDate: '2019-04-01',
    familienzulagen: '',
    alimenteReceived: '',
    monthlyTax: '850',
    groceries: '450',
    communication: '85',
    mobility: '120',
    otherInsurance: '',
    debtPayments: '',
    alimentePaid: '',
    savingsGoal: '500',
    savingsAccount: '18500',
    bankName: 'ZKB',
    creditCard: 'one',
    loans: '',
    pension3a: '250',
    pension3b: '',
    investmentFunds: '',
  },
  versicherungen: {
    kkInsurer: 'CSS',
    kkModel: 'standard',
    kkPremium: '385',
    franchise: 'f1500',
    kkCardNumber: '80756 012345678',
    bvgInsurer: 'BVK Personalvorsorge',
    bvgContribution: '420',
    uvg: 'employer',
    liabilityInsurance: 'yes',
    liabilityAmount: '35',
    householdInsurance: 'yes',
    householdInsuranceAmount: '22',
    travelInsurance: 'TCS',
    cyberInsurance: '',
    autoInsurance: '',
    autoInsuranceAmount: '',
    ahvContribution: '',
  },
  ausbildung: {
    schoolName: 'ZHAW',
    educationLevel: 'bachelor',
    efzNumber: '',
    certifications: 'CAS Notfallpflege',
    employer: 'Kantonsspital Zürich',
    jobTitle: 'Pflegefachfrau HF',
    employmentStart: '2019-04-01',
    workPermit: 'swiss',
    workHoursPerWeek: '80',
    languages: 'Deutsch, Englisch, Französisch',
  },
  behoerden: {
    cantoneOfTaxation: 'ZH',
    taxId: 'ZH-2024-123456',
    taxFilingDeadline: '2026-09-30',
    pendingTaxReturns: '0',
    registryOffice: 'Kreisbüro 4',
    betreibungsStatus: 'none',
    courtCases: 'no',
    legalRepresentative: '',
    representativePhone: '',
    willMade: 'no',
  },
  notfall: {
    emergencyContact: 'Peter Muster',
    emergencyPhone: '+41 79 654 32 10',
    bloodType: 'aPos',
    allergies: 'Penicillin',
    medications: '',
    chronicDiseases: '',
    doctor: 'Dr. med. Lisa Brunner',
    doctorPhone: '+41 44 242 80 00',
    hospital: 'UniversitätsSpital Zürich',
    organDonor: 'yes',
    patientenverfuegung: 'no',
    vorsorgeauftrag: 'no',
    bestattungswuensche: 'no',
  },
};
