// Top ~80 chronische Krankheiten in der Schweiz (ICD-10 Codes)
// Quellen: BAG Gesundheitsstatistik, BFS Todesursachenstatistik, Obsan
const DISEASES = [
  ['E11', 'Diabetes mellitus Typ 2'],
  ['E10', 'Diabetes mellitus Typ 1'],
  ['I10', 'Bluthochdruck (Hypertonie)'],
  ['I25', 'Koronare Herzkrankheit'],
  ['I50', 'Herzinsuffizienz'],
  ['I48', 'Vorhofflimmern'],
  ['J44', 'COPD (chronisch obstruktive Lungenerkrankung)'],
  ['J45', 'Asthma bronchiale'],
  ['M54', 'Rückenschmerzen (chronisch)'],
  ['M16', 'Hüftarthrose (Coxarthrose)'],
  ['M17', 'Kniearthrose (Gonarthrose)'],
  ['M05', 'Rheumatoide Arthritis'],
  ['M81', 'Osteoporose'],
  ['G43', 'Migräne'],
  ['G40', 'Epilepsie'],
  ['G20', 'Parkinson-Krankheit'],
  ['G35', 'Multiple Sklerose'],
  ['G30', 'Alzheimer-Krankheit'],
  ['F32', 'Depression'],
  ['F41', 'Angststörung'],
  ['F20', 'Schizophrenie'],
  ['F31', 'Bipolare Störung'],
  ['F10', 'Alkoholabhängigkeit'],
  ['F50', 'Essstörung (Anorexie / Bulimie)'],
  ['F90', 'ADHS'],
  ['C50', 'Brustkrebs'],
  ['C34', 'Lungenkrebs'],
  ['C61', 'Prostatakrebs'],
  ['C18', 'Darmkrebs (Kolon)'],
  ['C43', 'Melanom (Hautkrebs)'],
  ['C73', 'Schilddrüsenkrebs'],
  ['N18', 'Chronische Niereninsuffizienz'],
  ['K50', 'Morbus Crohn'],
  ['K51', 'Colitis ulcerosa'],
  ['K21', 'Refluxkrankheit (GERD)'],
  ['K74', 'Leberzirrhose'],
  ['K80', 'Gallensteine'],
  ['E05', 'Schilddrüsenüberfunktion (Hyperthyreose)'],
  ['E03', 'Schilddrüsenunterfunktion (Hypothyreose)'],
  ['E66', 'Adipositas'],
  ['E78', 'Erhöhtes Cholesterin (Hypercholesterinämie)'],
  ['D50', 'Eisenmangelanämie'],
  ['L40', 'Psoriasis (Schuppenflechte)'],
  ['L20', 'Neurodermitis (atopische Dermatitis)'],
  ['H40', 'Glaukom (Grüner Star)'],
  ['H25', 'Katarakt (Grauer Star)'],
  ['H81', 'Morbus Menière'],
  ['I73', 'Periphere arterielle Verschlusskrankheit (PAVK)'],
  ['I83', 'Krampfadern (Varizen)'],
  ['I63', 'Schlaganfall (Apoplex)'],
  ['J30', 'Heuschnupfen (allergische Rhinitis)'],
  ['N40', 'Gutartige Prostatavergrösserung'],
  ['N80', 'Endometriose'],
  ['E84', 'Zystische Fibrose (Mukoviszidose)'],
  ['G47', 'Schlafapnoe'],
  ['M35', 'Fibromyalgie'],
  ['K90', 'Zöliakie'],
  ['B20', 'HIV-Infektion'],
  ['M10', 'Gicht'],
  ['I27', 'Pulmonale Hypertonie'],
  ['G70', 'Myasthenia gravis'],
  ['E21', 'Hyperparathyreoidismus'],
  ['D69', 'Thrombozytopenie'],
  ['M45', 'Morbus Bechterew'],
  ['G25', 'Essentieller Tremor'],
  ['I42', 'Kardiomyopathie'],
  ['N03', 'Glomerulonephritis'],
  ['J84', 'Lungenfibrose'],
  ['E70', 'Phenylketonurie (PKU)'],
  ['M32', 'Lupus erythematodes'],
  ['K86', 'Chronische Pankreatitis'],
];

export function searchDiseases(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return DISEASES
    .filter(([code, name]) => name.toLowerCase().includes(q) || code.toLowerCase().includes(q))
    .slice(0, 8)
    .map(([code, name]) => ({ code, name }));
}
