// Top ~100 häufig verschriebene Medikamente in der Schweiz
// Quelle: Helsana Arzneimittelreport, BAG Spezialitätenliste (öffentlich)
// Format: [Handelsname, Wirkstoff, Standarddosis, Einheit]
export const MEDICATIONS = [
  ['Dafalgan', 'Paracetamol', '500-1000', 'mg'],
  ['Panadol', 'Paracetamol', '500', 'mg'],
  ['Aspirin', 'Acetylsalicylsäure', '500', 'mg'],
  ['Aspirin Cardio', 'Acetylsalicylsäure', '100', 'mg'],
  ['Ibuprofen', 'Ibuprofen', '400', 'mg'],
  ['Irfen', 'Ibuprofen', '400', 'mg'],
  ['Voltaren', 'Diclofenac', '50', 'mg'],
  ['Mefenacid', 'Mefenaminsäure', '500', 'mg'],
  ['Ponstan', 'Mefenaminsäure', '500', 'mg'],
  ['Tramadol', 'Tramadol', '50', 'mg'],
  ['Novalgin', 'Metamizol', '500', 'mg'],
  ['Metformin', 'Metformin', '500-1000', 'mg'],
  ['Glucophage', 'Metformin', '850', 'mg'],
  ['Januvia', 'Sitagliptin', '100', 'mg'],
  ['Jardiance', 'Empagliflozin', '10', 'mg'],
  ['Ozempic', 'Semaglutid', '0.25-1', 'mg'],
  ['Lisinopril', 'Lisinopril', '5-20', 'mg'],
  ['Enalapril', 'Enalapril', '5-20', 'mg'],
  ['Losartan', 'Losartan', '50-100', 'mg'],
  ['Candesartan', 'Candesartan', '8-16', 'mg'],
  ['Valsartan', 'Valsartan', '80-160', 'mg'],
  ['Amlodipin', 'Amlodipin', '5-10', 'mg'],
  ['Bisoprolol', 'Bisoprolol', '2.5-10', 'mg'],
  ['Metoprolol', 'Metoprolol', '50-100', 'mg'],
  ['Atenolol', 'Atenolol', '50-100', 'mg'],
  ['Torasemid', 'Torasemid', '5-10', 'mg'],
  ['Hydrochlorothiazid', 'Hydrochlorothiazid', '12.5-25', 'mg'],
  ['Atorvastatin', 'Atorvastatin', '10-40', 'mg'],
  ['Sortis', 'Atorvastatin', '20', 'mg'],
  ['Rosuvastatin', 'Rosuvastatin', '5-20', 'mg'],
  ['Crestor', 'Rosuvastatin', '10', 'mg'],
  ['Simvastatin', 'Simvastatin', '20-40', 'mg'],
  ['Pravastatin', 'Pravastatin', '20-40', 'mg'],
  ['Marcoumar', 'Phenprocoumon', '3', 'mg'],
  ['Xarelto', 'Rivaroxaban', '10-20', 'mg'],
  ['Eliquis', 'Apixaban', '2.5-5', 'mg'],
  ['Pradaxa', 'Dabigatran', '110-150', 'mg'],
  ['Nexium', 'Esomeprazol', '20-40', 'mg'],
  ['Pantoprazol', 'Pantoprazol', '20-40', 'mg'],
  ['Omeprazol', 'Omeprazol', '20', 'mg'],
  ['Lansoprazol', 'Lansoprazol', '15-30', 'mg'],
  ['Sertralin', 'Sertralin', '50-100', 'mg'],
  ['Zoloft', 'Sertralin', '50', 'mg'],
  ['Cipralex', 'Escitalopram', '10-20', 'mg'],
  ['Citalopram', 'Citalopram', '20', 'mg'],
  ['Fluoxetin', 'Fluoxetin', '20', 'mg'],
  ['Venlafaxin', 'Venlafaxin', '75-150', 'mg'],
  ['Mirtazapin', 'Mirtazapin', '15-30', 'mg'],
  ['Quetiapin', 'Quetiapin', '25-300', 'mg'],
  ['Temesta', 'Lorazepam', '1', 'mg'],
  ['Lexotanil', 'Bromazepam', '3', 'mg'],
  ['Stilnox', 'Zolpidem', '10', 'mg'],
  ['Rivotril', 'Clonazepam', '0.5-2', 'mg'],
  ['Lyrica', 'Pregabalin', '75-150', 'mg'],
  ['Gabapentin', 'Gabapentin', '300-600', 'mg'],
  ['Levothyrox', 'Levothyroxin', '25-150', 'µg'],
  ['Euthyrox', 'Levothyroxin', '50-100', 'µg'],
  ['Prednisolon', 'Prednisolon', '5-20', 'mg'],
  ['Spiricort', 'Dexamethason', '0.5-4', 'mg'],
  ['Symbicort', 'Budesonid/Formoterol', '200/6', 'µg'],
  ['Ventolin', 'Salbutamol', '100', 'µg'],
  ['Seretide', 'Fluticason/Salmeterol', '250/50', 'µg'],
  ['Montelukast', 'Montelukast', '10', 'mg'],
  ['Cetirizin', 'Cetirizin', '10', 'mg'],
  ['Loratadin', 'Loratadin', '10', 'mg'],
  ['Xyzal', 'Levocetirizin', '5', 'mg'],
  ['Augmentin', 'Amoxicillin/Clavulansäure', '625', 'mg'],
  ['Amoxicillin', 'Amoxicillin', '500', 'mg'],
  ['Ciproxin', 'Ciprofloxacin', '500', 'mg'],
  ['Klacid', 'Clarithromycin', '500', 'mg'],
  ['Co-Amoxicillin', 'Amoxicillin/Clavulansäure', '1000', 'mg'],
  ['Nitrofurantoin', 'Nitrofurantoin', '100', 'mg'],
  ['Ritalin', 'Methylphenidat', '10-20', 'mg'],
  ['Concerta', 'Methylphenidat', '18-54', 'mg'],
  ['Tamsulosin', 'Tamsulosin', '0.4', 'mg'],
  ['Finasterid', 'Finasterid', '5', 'mg'],
  ['Allopurinol', 'Allopurinol', '100-300', 'mg'],
  ['Calcium D3', 'Calcium/Vitamin D3', '500/400', 'mg/IE'],
  ['Vi-De 3', 'Cholecalciferol', '4000', 'IE'],
  ['Magnesium', 'Magnesium', '300', 'mg'],
  ['Ferro-Gradumet', 'Eisensulfat', '325', 'mg'],
  ['Pradif', 'Tamsulosin', '0.4', 'mg'],
  ['Reminyl', 'Galantamin', '8-16', 'mg'],
  ['Aricept', 'Donepezil', '5-10', 'mg'],
  ['Levetiracetam', 'Levetiracetam', '500-1000', 'mg'],
  ['Tegretol', 'Carbamazepin', '200-400', 'mg'],
  ['Lamotrigin', 'Lamotrigin', '25-200', 'mg'],
  ['Cosentyx', 'Secukinumab', '150-300', 'mg'],
  ['Humira', 'Adalimumab', '40', 'mg'],
  ['MTX', 'Methotrexat', '7.5-25', 'mg'],
  ['Prednison', 'Prednison', '5-50', 'mg'],
  ['Isotretinoin', 'Isotretinoin', '10-40', 'mg'],
  ['Pille (diverse)', 'Ethinylestradiol/Gestagen', '', ''],
  ['Nuvaring', 'Etonogestrel/Ethinylestradiol', '', ''],
  ['Viagra', 'Sildenafil', '50', 'mg'],
  ['Cialis', 'Tadalafil', '10-20', 'mg'],
];

export function searchMedications(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return MEDICATIONS
    .filter(([name, substance]) =>
      name.toLowerCase().includes(q) || substance.toLowerCase().includes(q)
    )
    .slice(0, 8)
    .map(([name, substance, dose, unit]) => ({ name, substance, dose, unit }));
}
