// ─── Document Expiration → Reminder Linking ────────────────
// Scans documents for expiry dates and creates/updates reminders
// in the Calendar system. Runs on app load and when documents change.
// Local-first: reads or5_docs, writes to or5_reminders.

const REMINDERS_KEY = 'or5_reminders';
const DOC_REMINDER_PREFIX = 'doc_expiry_';

const loadReminders = () => {
  try { return JSON.parse(localStorage.getItem(REMINDERS_KEY) || '[]'); }
  catch { return []; }
};

const saveReminders = (reminders) => {
  localStorage.setItem(REMINDERS_KEY, JSON.stringify(reminders));
};

const todayISO = () => new Date().toISOString().split('T')[0];

// Generates a stable ID for a document-linked reminder
const docReminderId = (docId) => DOC_REMINDER_PREFIX + docId;

/**
 * Sync document expiry dates with the reminder system.
 * - Creates reminders for documents with expiry dates (30 days before)
 * - Updates due dates if the document expiry changes
 * - Removes reminders if the document is deleted or expiry is cleared
 *
 * @param {Array} documents - Array of document objects from or5_docs
 * @param {Function} t - Translation function (optional)
 * @returns {Object} { created: number, updated: number, removed: number }
 */
export const syncDocumentReminders = (documents, t) => {
  const reminders = loadReminders();
  let created = 0, updated = 0, removed = 0;

  // Get all doc-linked reminder IDs
  const docReminderIds = new Set(
    reminders.filter(r => r.id.startsWith(DOC_REMINDER_PREFIX)).map(r => r.id)
  );

  // Get all document IDs that have expiry dates
  const docsWithExpiry = (documents || []).filter(d => d.expiryDate);
  const activeDocIds = new Set(docsWithExpiry.map(d => docReminderId(d.id)));

  // Remove reminders for deleted docs or docs without expiry
  const toRemove = [...docReminderIds].filter(id => !activeDocIds.has(id));
  let updatedReminders = reminders.filter(r => !toRemove.includes(r.id));
  removed = toRemove.length;

  // Create or update reminders for docs with expiry
  for (const doc of docsWithExpiry) {
    const id = docReminderId(doc.id);
    const existing = updatedReminders.find(r => r.id === id);

    // Calculate reminder date: 30 days before expiry
    const expiryDate = new Date(doc.expiryDate);
    const reminderDate = new Date(expiryDate.getTime() - 30 * 86400000);
    const reminderISO = reminderDate.toISOString().split('T')[0];

    const title = t
      ? t('docReminder.title', { name: doc.fileName || doc.docType || 'Document' })
      : 'Document expires: ' + (doc.fileName || doc.docType || 'Document');

    if (existing) {
      // Update if date changed
      if (existing.dueDate !== reminderISO) {
        existing.dueDate = reminderISO;
        existing.title = title;
        existing.done = false;
        existing.completedDate = null;
        updated++;
      }
    } else {
      // Create new reminder
      updatedReminders.push({
        id,
        title,
        dueDate: reminderISO,
        category: 'admin',
        recurrence: 'once',
        notes: t
          ? t('docReminder.notes', { date: doc.expiryDate })
          : 'Expires on ' + doc.expiryDate,
        done: false,
        completedDate: null,
        createdDate: todayISO(),
        linkedDocId: doc.id,
        autoGenerated: true,
      });
      created++;
    }
  }

  if (created > 0 || updated > 0 || removed > 0) {
    saveReminders(updatedReminders);
  }

  return { created, updated, removed };
};

/**
 * Check if a document has a linked reminder
 */
export const hasDocumentReminder = (docId) => {
  const reminders = loadReminders();
  return reminders.some(r => r.id === docReminderId(docId));
};

/**
 * Get the reminder linked to a document
 */
export const getDocumentReminder = (docId) => {
  const reminders = loadReminders();
  return reminders.find(r => r.id === docReminderId(docId)) || null;
};
